name: Deploy Sketches to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for deploying to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Sketches
        run: |
          mkdir -p dist
          for d in sketches/*/ ; do
            if [ -f "$d/package.json" ]; then
              echo "Building $d..."
              cd $d
              npm ci
              npm run build
              cd ../..
              mkdir -p dist/$(basename $d)
              cp -r $d/dist/* dist/$(basename $d)/
            fi
          done

      - name: Copy Landing Page
        run: |
          cp landing-page/index.html dist/index.html
          cp landing-page/favicon.png dist/favicon.png
          cp landing-page/sketches.json dist/sketches.json
          cp -r landing-page/thumbnails dist/thumbnails

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages